name: evip2_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=2.7.15
  - numpy=1.16.4
  - cython=0.29.15
  - pandas=0.24.2
  - scipy=1.2.1
  - cmappy=3.2.0
  - matplotlib=2.2.5
  - matplotlib-base=2.2.5
  - rpy2=2.8.6
  - pytables=3.5.2
  - blessings=1.7
  - r=3.5.1
  - bioconductor-deseq2=1.22.1
  - bioconductor-tximport=1.12.1
  - bioconductor-tximportdata=1.12.0
  - bioconductor-ensembldb=2.6.3
  - bioconductor-ensdb.hsapiens.v86=2.99.0
  - bioconductor-rhdf5=2.28.0
  - bioconductor-rhdf5lib=1.6.0
  - pillow=6.2.1
  - pip=20.0.2
  - pip:
    - configparser==4.0.2
    - kerneltree==0.0.5
    - pygeno==1.2.8
    - rabadb==1.0.5
    - upsetplot==0.4.0
